export const DEFAULT_RESOLUTIONS = [
  "Drink more water", "Read 12 books", "Go to the gym", "Save money", "Learn a new skill",
  "Quit bad habit", "Eat more veggies", "Call parents often", "Travel somewhere new", "Cook at home",
  "Sleep 8 hours", "Limit screen time", "Volunteer", "Start a journal", "Walk 10k steps",
  "Learn a language", "Meditate daily", "Declutter home", "Meet new people", "Try a new hobby",
  "Write a letter", "Take the stairs", "No sugar for a month", "Be kind to yourself", "Donate old clothes",
  "Wake up early", "Floss daily", "Limit caffeine", "Go for a run", "Do yoga",
  "Plant a garden", "Learn to code", "Read the news", "Watch a documentary", "Listen to podcasts",
  "Visit a museum", "Go hiking", "Ride a bike", "Swim once a week", "Join a club",
  "Host a dinner", "Bake a cake", "Learn to dance", "Paint a picture", "Take photos",
  "Write a poem", "Sing in the shower", "Learn an instrument", "Go to a concert", "Watch a play",
  "Clean the garage", "Organize closet", "Wash the car", "Fix something broken", "Recycle more",
  "Use less plastic", "Compost waste", "Buy local", "Walk the dog", "Play with pets",
  "Call a friend", "Send a postcard", "Give a compliment", "Smile at strangers", "Hold the door",
  "Tip generously", "Donate to charity", "Help a neighbor", "Teach someone", "Mentor a junior",
  "Learn first aid", "Give blood", "Vote in elections", "Attend a town hall", "Sign a petition",
  "Save for retirement", "Invest in stocks", "Pay off debt", "Create a budget", "Track expenses",
  "Cancel subscriptions", "Buy second hand", "Repair clothes", "Cook in bulk", "Pack lunch",
  "Eat fruit daily", "Cut out soda", "Drink green tea", "Take vitamins", "Get a checkup",
  "Go to the dentist", "Wear sunscreen", "Moisturize skin", "Stretch daily", "Stand up more",
  "Take deep breaths", "Practice gratitude", "Forgive someone", "Let go of anger", "Be patient",
  "Listen more", "Speak less", "Avoid gossip", "Be honest", "Keep promises",
  "Arrive on time", "Plan the week", "Set daily goals", "Review progress", "Celebrate wins",
  "Learn history", "Study science", "Read poetry", "Explore art", "Watch classic movies",
  "Listen to jazz", "Learn chess", "Solve puzzles", "Play board games", "Do crosswords",
  "Learn magic tricks", "Juggle balls", "Whistle a tune", "Tell a joke", "Laugh more",
  "Cry if needed", "Hug someone", "Hold hands", "Say I love you", "Kiss your partner",
  "Play with kids", "Read to children", "Call grandparents", "Visit family", "Host a party",
  "Go on a date", "Take a vacation", "Have a staycation", "Visit a park", "Go to the beach",
  "Watch the sunset", "Stargaze at night", "Camp outdoors", "Build a fire", "Roast marshmallows",
  "Go fishing", "Go birdwatching", "Identify trees", "Pick flowers", "Grow herbs",
  "Make jam", "Pickle vegetables", "Bake bread", "Make pasta", "Grill outside",
  "Try sushi", "Eat spicy food", "Drink wine", "Brew coffee", "Make tea",
  "Learn origami", "Knitting or crochet", "Sew a button", "Iron a shirt", "Polish shoes",
  "Change a tire", "Check oil level", "Drive safely", "Walk to work", "Carpool often",
  "Use public transit", "Fly less", "Conserve water", "Turn off lights", "Unplug devices",
  "Update passwords", "Back up data", "Clean email inbox", "Organize photos", "Delete old apps",
  "Learn Excel", "Master a shortcut", "Type faster", "Write a blog", "Start a vlog",
  "Take a selfie", "Record a video", "Edit a movie", "Mix a song", "DJ a party",
  "Learn to draw", "Sketch a face", "Doodle in class", "Color in a book", "Make a collage",
  "Build a model", "Fly a kite", "Throw a frisbee", "Kick a ball", "Shoot a hoop",
  "Play tennis", "Play badminton", "Play ping pong", "Go bowling", "Play pool",
  "Throw darts", "Play cards", "Learn poker", "Do a magic trick", "Build a card tower",
  "Solve a riddle", "Tell a story", "Write a novel", "Read a biography", "Read a classic",
  "Read a comic", "Read a magazine", "Read a newspaper", "Visit the library", "Borrow a book"
];
